-- anything that is not 'local', is automatically global
VIRTUAL_WIDTH = 224
VIRTUAL_HEIGHT = 256

WINDOW_WIDTH = VIRTUAL_WIDTH * 3
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 3

ALIEN_WIDTH = 12
ALIEN_HEIGHT = 12

SHIP_WIDTH = 12
SHIP_HEIGHT = 12
SHIP_SPEED = 100

ALIENS_WIDE = 11 -- columns of aliens
ALIENS_TALL = 5  -- rows of aliens
ALIEN_PADDING = 6 -- padding between aliens

PROJECTILE_LENGTH = 5
PROJECTILE_SPEED = 120
